# Generated by Django 2.2.4 on 2019-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190905_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
